FROM ubuntu:18.04
RUN apt update && apt install -y wget iputils-ping vim net-tools lsof sudo less netcat dnsutils iproute2 tcpdump tcptrack
RUN apt install -y mysql-server-5.7

# If DB is empty, inital DB can be created with:
# mysqld --initialize
