FROM ubuntu:18.04

EXPOSE 3000

WORKDIR /app

RUN apt update
RUN apt install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh && bash nodesource_setup.sh && rm -f nodesource_setup.sh
RUN apt install -y nodejs build-essential nginx netcat lsof vim
RUN npm install -g npx

RUN mkdir -p /app
