# This is debian based system

FROM ruby:2.4.6-stretch
RUN apt update && apt install -y wget iputils-ping vim net-tools lsof sudo less netcat dnsutils iproute2 tcpdump tcptrack psmisc
RUN apt install -y mysql-client iptables nscd

RUN gem install rails -v 5.1.6.2

RUN mkdir -p /app

# Just install standard gems
RUN mkdir -p /tmp/app && cd /tmp/app && rails new . --api --force --database=mysql && bundle && rm -rf /tmp/app
