version: '3.5'

# mkdir -p data/primary && mkdir -p data/secondary && mkdir -p data/rails && docker-compose build && docker-compose down && docker-compose up -d && docker-compose ps

services:
  # https://hub.docker.com/_/mysql
  mysql-1:
    # docker exec -it mysql-1 bash
    # mysql -h mysql-1 -u root -pexample
    container_name: mysql-1
    hostname: mysql-1
    build:
      context: .
      dockerfile: Dockerfile-mysql-primary
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: app
      MYSQL_PASSWORD: ${APP_PASSWORD}
      MYSQL_DATABASE: my-app
      REPLICATION_USER: replication
      REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
    ports:
      - 33061:3306
    volumes:
      - ./data/primary:/var/lib/mysql
      - ./mysqld-primary.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./001-initialize-primary.sh:/docker-entrypoint-initdb.d/001-initialize.sh
      - ./001-initialize-primary.sql:/docker-entrypoint-initdb.d/001-initialize.sql
  mysql-2:
    # docker exec -it mysql-2 bash
    # mysql -h mysql-2 -u root -pexample
    container_name: mysql-2
    hostname: mysql-2
    build:
      context: .
      dockerfile: Dockerfile-mysql-secondary
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      # Replication fails if users created before the cluster building (some differences?)!
      # MYSQL_USER: app
      # MYSQL_PASSWORD: ${APP_PASSWORD}
      # MYSQL_DATABASE: my-app
      REPLICATION_USER: replication
      REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
    ports:
      - 33062:3306
    volumes:
      - ./data/secondary:/var/lib/mysql
      - ./mysqld-secondary.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./001-initialize-secondary.sh:/docker-entrypoint-initdb.d/001-initialize.sh
      - ./001-initialize-secondary.sql:/docker-entrypoint-initdb.d/001-initialize.sql
  mysql-monitor:
    # docker exec -it mysql-monitor bash
    container_name: mysql-monitor
    hostname: mysql-monitor
    build:
      context: .
      dockerfile: Dockerfile-mysql-monitor
    depends_on:
      - "mysql-1"
      - "mysql-2"
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      REPLICATION_USER: replication
      REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
      CDN_AUTH_KEY: ${CDN_AUTH_KEY}
      CDN_AUTH_EMAIL: ${CDN_AUTH_EMAIL}
      CDN_API_ADDRESS: ${CDN_API_ADDRESS}
    command: >
      bash -c "
      tail -F /tmp/mysqlfailover.log > /dev/console
      & sleep 5
      && mysqlfailover --force --master=root:${ROOT_PASSWORD}@mysql-1:3306 --discover-slaves-login=root:${ROOT_PASSWORD} --daemon nodetach --log=/tmp/mysqlfailover.log --pedantic --exec-after=/tmp/mysqlfailover_exec_after.sh --verbose auto
      ; tail -F /dev/null"
    user: 'root'
    volumes:
      # Docker should be installed as well
      - /var/run/docker.sock:/var/run/docker.sock
      - ./mysqlfailover_exec_after.sh:/tmp/mysqlfailover_exec_after.sh
      - ./mysqlswitchover_exec_after.sh:/tmp/mysqlswitchover_exec_after.sh
    stdin_open: true
    tty: true
  rails:
    container_name: rails
    hostname: rails
    build:
      context: .
      dockerfile: Dockerfile-rails
    command: >
      bash -c "
      cd /root/app && rails db:migrate ; rails g model Example name:string ; rails s -p 3000 -b 0.0.0.0
      ; tail -F /dev/null"
    volumes:
      - ./rails/database.yml:/root/app/config/database.yml
      - ./rails/routes.rb:/root/app/config/routes.rb
      - ./rails/examples_controller.rb:/root/app/app/controllers/api/v1/examples_controller.rb
    ports:
      - "3000:3000"
