FROM ubuntu:18.04
RUN apt update && apt install -y wget iputils-ping vim net-tools lsof sudo less netcat dnsutils iproute2 tcpdump tcptrack psmisc jq
RUN apt install -y python python-pip mysql-client screen \
&& pip install mysql-connector \
&& wget https://github.com/mysql/mysql-utilities/archive/release-1.6.5.tar.gz \
&& tar xf release-1.6.5.tar.gz \
&& cd mysql-utilities-release-1.6.5 \
&& python ./setup.py build \
&& python ./setup.py install

RUN apt install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
RUN apt update && apt install -y docker-ce=5:18.09.6~3-0~ubuntu-bionic docker-ce-cli=5:18.09.6~3-0~ubuntu-bionic containerd.io

RUN mkdir -p /scripts
