# Master blacklisting issue
# https://github.com/taskrabbit/makara/issues/101

default: &default
  # Parameter to explor if this is allowed here
  reconnect: true
  #timeout: 5000
  #reaping_frequency: 10
  #connection_timeout: 5
  #read_timeout: 5
  url: mysql2-makara:///
  makara:
    # master_strategy: failover
    # master_node_selector: 'Makara::NodeSelectors::SingleWithFailover'
    # slave_node_selector: 'Makara::NodeSelectors::RoundRobin'
    sticky: true
    # Paramters to explore
    # slave_strategy: failover
    #master_ttl: 5
    #rescue_connection_failures: false
    blacklist_duration: 0
    connections:
      - role: master
        name: master
        url: 'mysql2://app:example@mysql-master:3306/my-app'
      - role: replica
        name: replica
        url: 'mysql2://app:example@mysql-replica:3306/my-app'

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
