# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c5d9599545b9acdeb8ea61ee18dea1760d96760ce2e7af3cb6fefbb8404bb029d7fd035dce1acbe89b248170ecdfc028adccda57b7bd3b6cfb2b9a903a9d4a55

test:
  secret_key_base: cc80bdf9f0569117a0ec1e5bd2132902c194459491146b18aa86d06035458a2a63a5939cd0de139ee147406fe1da970646db5aafdcb134976f46256f868b4f51

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
