version: '2'

services:
  whale:
    hostname: monitor.local
    build:
      context: .
      dockerfile: Dockerfile-monitor
    command: >
      bash -c "true
      ; tail -F /dev/null"
    user: 'root'
    volumes:
     - ./data:/data
    working_dir: /data/monitor
  dolphin:
    hostname: master.local
    build:
      context: .
      dockerfile: Dockerfile-master
    command: >
      bash -c "chown -R mysql:mysql /data/master /var/run/mysqld /var/lib/mysql
      ; usermod -d /data/master/db/ mysql
      ; /etc/init.d/mysql start
      ; mysql -u root -e \"UPDATE mysql.user SET authentication_string=PASSWORD('password') WHERE  User='debian-sys-maint' AND Host='localhost'; flush privileges;\"
      ; mysql -u root -e \"create user 'slaveuser'@'%' identified by 'slavepassword'\"
      ; mysql -u root -e \"grant replication slave on *.* to 'slaveuser'@'%'\"
      ; mysql -u root -e \"create database animals\"
      ; mysql -u root -e \"create table animals.list (name varchar(20))\"
      ; tail -F /dev/null"
    user: 'root'
    ports:
     - "33061:33061"
    volumes:
     - ./data:/data
     - ./etc-mysql-mysql.conf.d-mysql.cnf-master:/etc/mysql/mysql.conf.d/mysqld.cnf
     - ./etc-mysql-debian.cnf-master:/etc/mysql/debian.cnf
    working_dir: /data/master
    environment:
     - MYSQL_ROOT_PASSWORD=root
  goldfish:
    hostname: slave.local
    build:
      context: .
      dockerfile: Dockerfile-slave
    command: >
      bash -c "chown -R mysql:mysql /data/slave /var/run/mysqld /var/lib/mysql
      ; usermod -d /data/slave/db/ mysql
      ; /etc/init.d/mysql start
      ; mysql -u root -e \"UPDATE mysql.user SET authentication_string=PASSWORD('password') WHERE  User='debian-sys-maint' AND Host='localhost'; flush privileges;\"
      ; tail -F /dev/null"
    user: 'root'
    ports:
     - "33062:33062"
    volumes:
     - ./data:/data
     - ./etc-mysql-mysql.conf.d-mysql.cnf-slave:/etc/mysql/mysql.conf.d/mysqld.cnf
     - ./etc-mysql-debian.cnf-slave:/etc/mysql/debian.cnf
    working_dir: /data/slave
    environment:
     - MYSQL_ROOT_PASSWORD=root
