FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="/root/.rbenv/versions/2.4.5/bin/root/.rbenv/bin:${PATH}"
RUN mkdir -p /myapp
RUN touch /myapp/Gemfile
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y git curl libssl-dev libreadline-dev zlib1g-dev autoconf bison build-essential libyaml-dev libreadline-dev libncurses5-dev libffi-dev libgdbm-dev nodejs libsqlite3-dev tzdata libmysqlclient-dev \
&& curl -sL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash - \
&& echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc \
&& echo 'eval "$(rbenv init -)"' >> ~/.bashrc \
&& source ~/.bashrc \
&& rbenv install 2.4.5 \
&& rbenv global 2.4.5 \
&& gem update --system \
&& gem install rails -v 5.1.6 \
&& touch /myapp/Gemfile \
&& touch /myapp/Gemfile.lock \
&& cat /myapp/Gemfile 2>/dev/null | grep [a-zA-Z] || printf "source 'https://rubygems.org'\ngem 'rails', '5.1.6'\n" > /myapp/Gemfile \
&& cd /myapp && bundle install && rails new . --api --force --database=mysql
WORKDIR /myapp
# CMD bundle exec rails s -p 3000 -b 0.0.0.0

# Build this:
#
# docker build -t rails -f Dockerfile-rails .
#
