version: '2'

services:
  whale:
    hostname: monitor.local
    build:
      context: .
      dockerfile: Dockerfile-monitor
    command: >
      bash -c "/etc/init.d/mysql start
      && tail -F /dev/null"
    user: 'root'
    volumes:
     - ./data:/data
    working_dir: /data
  dolphin:
    hostname: master.local
    build:
      context: .
      dockerfile: Dockerfile-master
    command: >
      bash -c "/etc/init.d/mysql start
      && tail -F /dev/null"
    user: 'root'
    ports:
     - "33061:33061"
    volumes:
     - ./data:/data
     - ./etc-mysql-mysql.conf.d-mysql.cnf-master:/etc/mysql/mysql.conf.d/mysql.cnf
    working_dir: /root
    environment:
     - MYSQL_ROOT_PASSWORD=root
  goldfish:
    hostname: slave.local
    build:
      context: .
      dockerfile: Dockerfile-slave
    command: "tail -F /dev/null"
    user: 'root'
    ports:
     - "33062:33062"
    volumes:
     - ./data:/data
     - ./etc-mysql-mysql.conf.d-mysql.cnf-slave:/etc/mysql/mysql.conf.d/mysql.cnf
    working_dir: /root
    environment:
     - MYSQL_ROOT_PASSWORD=root
