# This is debian based system
FROM ruby:2.4.6-stretch
# RUN mkdir -p /data/rails
RUN apt update \
&& touch /data/rails/Gemfile.lock \
&& cat /data/rails/Gemfile 2>/dev/null | grep [a-zA-Z] || printf "source 'https://rubygems.org'\ngem 'rails', '5.1.6'\n" > /data/rails/Gemfile \
&& cd /data/rails && bundle install && rails new . --api --force --database=mysql
# WORKDIR /data/rails
# CMD bundle exec rails s -p 3000 -b 0.0.0.0

# Build and run this container:
# docker build -t rails -f Dockerfile-rails .
# docker run -it rails /bin/bash
#
# Build and run this container using docker-compose:
# docker-compose build orca
#
# Experiment with parent container:
# docker run -it ruby:2.4.5 /bin/bash
