FROM ubuntu:18.04
RUN apt update && apt install -y wget iputils-ping python python-pip mysql-client vim \
&& pip install mysql-connector \
&& wget https://github.com/mysql/mysql-utilities/archive/release-1.6.5.tar.gz \
&& tar xf release-1.6.5.tar.gz \
&& cd mysql-utilities-release-1.6.5 \
&& python ./setup.py build \
&& python ./setup.py install
