development:
  host: 192.168.250.246
  port: 3306
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: testdb
  pool: 5
  username: newuser
  password: password
  socket: /tmp/mysqld.sock
