default: &default
  url: mysql2-makara:///
  makara:
    sticky: true
    connections:
      - role: master
        name: primary
        url: 'mysql2://root:password@localhost:33061/testdb'
      - name: replica
        url: 'mysql2://root:password@localhost:33062/testdb'

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
