default: &default
  url: mysql2-makara:///
  makara:
    sticky: true
    connections:
      - role: master
        name: primary
        url: 'mysql2://newuser:password@192.168.250.246:3306/testdb'
      - name: replica
        url: 'mysql2://newuser:password@192.168.250.207:3306/testdb'

development:
  <<: *default

production:
  <<: *default
